name: tabulate
description: Dart library for displaying ascii tables.
version: 1.0.0
homepage: https://github.com/Mhwmd/dart-tabulate

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
