name: dart_tabulate
description: Dart library for displaying ascii tables.
author: Mohammad Yaghubkhani <mhwmdyaghubkhani@gmail.com>
version: 1.0.0
homepage: https://github.com/Mhwmd/dart-tabulate

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  characters: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

